#cloud-config

users:
  - name: ansible
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDU4vp/4vCsyNg29+6rLmVaWK2nXmgrawzWivPCGfSF4D+/AGy/SUjlTvKbCySuVOw79IzS63VP/1NdE5ylkQlyRLH3GuVFzPzXA3KG+SR4M8Xl+HqzqEuGSx1+XCigcRbaBbepJUpz6zm2OuDf36gyB1HJI40xRTphQXD4ypM1fhEFAXD+ZKAqOP0rQbCYmPkx18/crxNOUUjD83LBahqxo7sTEb4LQg0FZOP2Nhhc9m6MyLmzJY8+MP3xbh4nUHL7bF1T5sqiOB81a2oCQ6bIhvJ8zfjVfYoaeDpAmOLUhOb5ld0mrjRAUCbRh8xAz8HGOMfqTVH3O9EfLiMQTtEJp0dImkL/EFpO4CwJ6NI1RxLm7z0GKArTNCoBi3NmUNdN68UEOQR2FT/8mbVffBAvuVrcSXWDzQz+qt0KHf1O1J/D3WmKAN79msbAQ5wuwTZcahk36EuV3VJVGtNUeSVfGkOJ9LGlmlugKE1EEcljGKomJHD9iTbdmNsIQxqFRXk=
